### ISSUE TITLE
Problem: Cannot authenticate an EventSource

### ISSUE THREAD

**Issue by Jeroenbruinsma** [Codaisseur/game-project#12]
**Summary**
I'm trying to get the eventsource working in react but keep getting the error401 (Unauthorized).

**Steps:**
1. In my terminal, I ran `http GET :5000/game Authorization:"Bearer <JWT>" gameId=26 --stream`. It worked.
2. In my client-side code, I wrote `source = new EventSource(this.url + "/game" ,  { authorizationHeader: "Bearer " + <JWT>  })`. It didn't work.

**Expected result:**
Receive the stream from the back-end including some data 

**Actual result:**
`GET http://localhost:5000/game 401 (Unauthorized)`

**Comment by Jeroenbruinsma** [comment]
Uses the headers in stead of the  auth header

source = new EventSource(this.url + "/game" ,  
  { 
    headers: {
      'Authorization': "Bearer " + <JWT>
    }
  })

**Comment by Jeroenbruinsma** [comment]
Solution: use `headers` instead of `authheader`.

```
source = new EventSource(this.url + "/game",
  {
    headers: {
      Authorization: "Bearer "
    }
  }
)
```

**Comment by lakylekidd** [comment]
MR. Jeroen Ruiswhatever

what YOU need to do is `npm i event-source-polyfill`
Then, import it: `import { EventSourcePolyfill } from 'event-source-polyfill';` and then, instead of `new EventSource(url)` you need to use `new EventSourcePolyfill(url, { headers: { 'Authorization': 'Bearer token'}})`....

BOOM!
You're welcome
